-------------------------------------------------------------------------------
Test set: org.apache.ratis.server.simulation.TestServerRestartWithSimulatedRpc
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.615 s <<< FAILURE! - in org.apache.ratis.server.simulation.TestServerRestartWithSimulatedRpc
testRestartWithCorruptedLogEntryWithException(org.apache.ratis.server.simulation.TestServerRestartWithSimulatedRpc)  Time elapsed: 1.095 s  <<< FAILURE!
java.lang.AssertionError: The test "restart-fail-ChecksumException" does not throw anything.
	at org.apache.ratis.BaseTest.testFailureCase(BaseTest.java:159)
	at org.apache.ratis.BaseTest.testFailureCase(BaseTest.java:167)
	at org.apache.ratis.server.ServerRestartTests.testRestartWithCorruptedLogEntryWithException(ServerRestartTests.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

